{% set name = "unstructured" %}
{% set version = "0.13.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unstructured-{{ version }}.tar.gz
  sha256: f2ed56bffce46dc1e77ab13732a6d6ff989a7793df0ccc64bb63e58af242aa39

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.12
    - pip
  run:
    - python >=3.9,<3.12
    - backoff
    - beautifulsoup4
    - certifi ==2024.2.2
    - chardet
    - charset-normalizer ==3.3.2
    - click ==8.1.7
    - dataclasses-json
    - emoji
    - filetype
    - idna ==3.6
    - joblib ==1.3.2
    - jsonpath-python ==1.0.6
    - langdetect
    - lxml
    - marshmallow ==3.20.2
    - mypy_extensions ==1.0.0
    - nltk
    - numpy
    - packaging ==23.2
    - python-dateutil ==2.8.2
    - python-iso639
    - python-magic
    - rapidfuzz
    - regex ==2023.12.25
    - requests
    - six ==1.16.0
    - soupsieve ==2.5
    - tabulate
    - tqdm ==4.66.2
    - typing-extensions
    - typing_inspect ==0.9.0
    - unstructured-client <=0.18.0
    - urllib3 ==1.26.18
    - wrapt

test:
  imports:
    - unstructured
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Unstructured-IO/unstructured
  summary: A library that prepares raw documents for downstream ML tasks.
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jan-janssen
