{% set name = "unstructured" %}
{% set version = "0.18.13" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/unstructured-{{ version }}.tar.gz
  sha256: 3ca6034d8647fef5c26b39bacae3d90a5f530f520bfd80f0e964bd5e084a0d50

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - ndjson
    - html5lib
    - typing_extensions
    - python-oxmsg
    - psutil
    - python >={{ python_min }},<3.13
    - backoff
    - beautifulsoup4
    - certifi =2024.2.2
    - chardet
    - charset-normalizer
    - click =8.1.7
    - dataclasses-json
    - emoji
    - filetype
    - idna =3.6
    - joblib =1.3.2
    - jsonpath-python =1.0.6
    - langdetect
    - lxml
    - marshmallow =3.20.2
    - mypy_extensions =1.0.0
    - nltk
    - numpy
    - packaging =23.2
    - python-dateutil =2.8.2
    - python-iso639
    - python-magic
    - rapidfuzz
    - regex =2023.12.25
    - requests
    - six =1.16.0
    - soupsieve =2.5
    - tabulate
    - tqdm
    - typing-extensions
    - typing_inspect =0.9.0
    - unstructured-client
    - urllib3 =1.26.18
    - wrapt

test:
  imports:
    - unstructured
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Unstructured-IO/unstructured
  summary: A library that prepares raw documents for downstream ML tasks.
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jan-janssen
